version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - danirod
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - danirod
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: "bootstrap"
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - danirod
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: "ruby"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - dependencies
