require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'

# Allow scenario to describe Capybara E2E tests.
Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*.rb'

# I see nothing wrong with this.
RSpec/ExampleLength:
  Enabled: false

# Documentation in a Rails app? No thanks.
Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
