name: Push current trunk branch to the Docker registry
on:
  push:
    branches:
      - trunk
jobs:
  docker_registry:
    name: Push the website image to the registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Dockerfile
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/makigas:latest .
      - name: Push to GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username danirod --password-stdin
          docker push docker.pkg.github.com/${{ github.repository }}/makigas:latest
