name: SSH Deployment
on: [push]
jobs:
  deploy:
    name: Deploy into my server
    runs-on: ubuntu-latest
    steps:
    - name: Execute a remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker-compose --project-directory docker/makigas ps
